{
 "title": "Env KPIs",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "hostname", "label": "hostname", "query": "label_values(hostname)" }
  ]
 },
 "panels": [
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "GET",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (method) (increase(gin_requests_total{hostname=\"$hostname\", job=\"entity-server\", method=\"GET\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "PUT",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (method) (increase(gin_requests_total{hostname=\"$hostname\", job=\"entity-server\", method=\"PUT\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "POST",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (method) (increase(gin_requests_total{hostname=\"$hostname\", job=\"entity-server\", method=\"POST\",url!~\"/.*/api/.*/search/.*/.*\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "SEARCH",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (method) (increase(gin_requests_total{hostname=\"$hostname\", job=\"entity-server\", method=\"POST\",url=~\"/.*/api/.*/_msearch\"}[$__rate_interval]))"
    }
   ]
  },
  { "title": "95pc Response Times", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "RESPONSE-TIMES-GET",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(gin_request_duration_seconds_bucket{hostname=\"$hostname\", method=\"GET\", url!~\"/skyr3/api/R3V001-demo/sse\"}[$__rate_interval])) by (le))"
    }
   ]
  },
  {
   "title": "RESPONSE-TIMES-PUT",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(gin_request_duration_seconds_bucket{hostname=\"$hostname\", method=\"PUT\"}[$__rate_interval])) by (le))"
    }
   ]
  },
  {
   "title": "RESPONSE-TIMES-POST",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(gin_request_duration_seconds_bucket{hostname=\"$hostname\", method=\"POST\",url!~\"/.*/api/.*/search/.*/.*\"}[$__rate_interval])) by (le))"
    }
   ]
  },
  {
   "title": "RESPONSE-TIMES-SEARCH",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(gin_request_duration_seconds_bucket{hostname=\"$hostname\", method=\"POST\", url=~\"/.*/api/.*/_msearch\"}[$__rate_interval])) by (le))"
    }
   ]
  }
 ]
}