{
 "title": "User Interactions",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "hostname", "label": "hostname", "query": "label_values(hostname)" }
  ]
 },
 "panels": [
  { "title": "User Interactions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Logins",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (code) (increase(gin_requests_total{hostname=\"$hostname\", job=\"entity-server\",url=~\"/.*/api/.*/auth/login\"}[15m]))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Profile Updates",
   "type": "graph",
   "description": "Updates",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(increase ((gin_requests_total{hostname=\"$hostname\", job=\"entity-server\",method=\"PUT\", handler=\"amperfii-backend/cmd/entity-server/api.UpdateUserProfile\"}[15m])))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Opportunities",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(label_replace (sum by (method) (increase(gin_requests_total{hostname=\"$hostname\", job=\"entity-server\",url=~\"/.*/api/.*/opportu.*\", method=~\"POST|PUT\"}[15m])),\"method\",\"CREATES\",\"method\",\"PUT\"),\"method\",\"UPDATES\",\"method\",\"POST\")",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Playbooks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (method) (increase(gin_requests_total{hostname=\"$hostname\", job=\"entity-server\",url=~\"/.*/api/.*/playbooks-opportunity.*\", method =~\"PUT|POST\"}[15m]))"
    }
   ]
  },
  {
   "title": "User Interactions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (handler) (increase(gin_requests_total{hostname=\"$hostname\", job=\"entity-server\", method=~\"PUT|POST\", url!~\"/.*/api/.*/auth/.*\", handler!=\"amperfii-backend/internal/pkg/gin-util.ProxyHandler.func1\"}[15m]))",
     "legendFormat": "{{method}}"
    }
   ]
  }
 ]
}