server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://host-vishnu.nonprod.amperfii:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*log
- job_name: devops
  static_configs:
  - targets:
      - localhost
    labels:
      job: opslogs
      __path__: /home/ec2-user/logs/* 

